apiVersion:apps/v1
kind: Deployment
metadat:
  name:order-service
  labels:
    app: order-service
  spec:
    replicas: 2
    selector:
      matchLables:
        app: order-service
      spec:
        containers:
          -name: order-service
          image: gcr.io/HCL_HACKATHON/order-service:latest
          ports: 
            -ContainerPort: 3030
            env:
              - name: NODE_ENV
               value: "Dev"
